[package]
name = "vulcan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
image = "0.24.7"
imageproc = "0.23.0"
miette = { version = "5.10.0", features = ["fancy"] }
num = "0.4.1"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
inversion_list = { git = "https://github.com/DefaultSimon/inversion-list", rev = "ce474c22d07a507bf51163325a4908b168c0d440" }

